// Code generated by BobGen psql v0.46.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// Subscription is an object representing the database table.
type Subscription struct {
	ID          uuid.UUID           `db:"id,pk" `
	ServiceName string              `db:"service_name" `
	Price       int32               `db:"price" `
	UserID      uuid.UUID           `db:"user_id" `
	StartDate   time.Time           `db:"start_date" `
	EndDate     null.Val[time.Time] `db:"end_date" `
	CreatedAt   time.Time           `db:"created_at" `
	UpdatedAt   time.Time           `db:"updated_at" `
}

// SubscriptionSlice is an alias for a slice of pointers to Subscription.
// This should almost always be used instead of []*Subscription.
type SubscriptionSlice []*Subscription

// Subscriptions contains methods to work with the subscriptions table
var Subscriptions = psql.NewTablex[*Subscription, SubscriptionSlice, *SubscriptionSetter]("", "subscriptions", buildSubscriptionColumns("subscriptions"))

// SubscriptionsQuery is a query on the subscriptions table
type SubscriptionsQuery = *psql.ViewQuery[*Subscription, SubscriptionSlice]

func buildSubscriptionColumns(tableName string) subscriptionColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "service_name", "price", "user_id", "start_date", "end_date", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return subscriptionColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildSubscriptionColumn(tableName, "id"),
		ServiceName: buildSubscriptionColumn(tableName, "service_name"),
		Price:       buildSubscriptionColumn(tableName, "price"),
		UserID:      buildSubscriptionColumn(tableName, "user_id"),
		StartDate:   buildSubscriptionColumn(tableName, "start_date"),
		EndDate:     buildSubscriptionColumn(tableName, "end_date"),
		CreatedAt:   buildSubscriptionColumn(tableName, "created_at"),
		UpdatedAt:   buildSubscriptionColumn(tableName, "updated_at"),
	}
}

type subscriptionColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          subscriptionColumn
	ServiceName subscriptionColumn
	Price       subscriptionColumn
	UserID      subscriptionColumn
	StartDate   subscriptionColumn
	EndDate     subscriptionColumn
	CreatedAt   subscriptionColumn
	UpdatedAt   subscriptionColumn
}

// Alias returns the current table alias for the columns set.
func (c subscriptionColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (subscriptionColumns) AliasedAs(tableName string) subscriptionColumns {
	return buildSubscriptionColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c subscriptionColumns) Unqualified() subscriptionColumns {
	return buildSubscriptionColumns("")
}

func buildSubscriptionColumn(alias, name string) subscriptionColumn {
	return subscriptionColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type subscriptionColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c subscriptionColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c subscriptionColumn) ShouldOmitParens() bool {
	return true
}

// SubscriptionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SubscriptionSetter struct {
	ID          omit.Val[uuid.UUID]     `db:"id,pk" `
	ServiceName omit.Val[string]        `db:"service_name" `
	Price       omit.Val[int32]         `db:"price" `
	UserID      omit.Val[uuid.UUID]     `db:"user_id" `
	StartDate   omit.Val[time.Time]     `db:"start_date" `
	EndDate     omitnull.Val[time.Time] `db:"end_date" `
	CreatedAt   omit.Val[time.Time]     `db:"created_at" `
	UpdatedAt   omit.Val[time.Time]     `db:"updated_at" `
}

func (s SubscriptionSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.ServiceName.IsValue() {
		vals = append(vals, "service_name")
	}
	if s.Price.IsValue() {
		vals = append(vals, "price")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.StartDate.IsValue() {
		vals = append(vals, "start_date")
	}
	if s.EndDate.IsValue() || s.EndDate.IsNull() {
		vals = append(vals, "end_date")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s SubscriptionSetter) Overwrite(t *Subscription) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.ServiceName.IsValue() {
		t.ServiceName = s.ServiceName.MustGet()
	}
	if s.Price.IsValue() {
		t.Price = s.Price.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.StartDate.IsValue() {
		t.StartDate = s.StartDate.MustGet()
	}
	if s.EndDate.IsValue() || s.EndDate.IsNull() {
		t.EndDate = s.EndDate.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *SubscriptionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Subscriptions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ServiceName.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ServiceName.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Price.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Price.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.UserID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.UserID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.StartDate.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.StartDate.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.EndDate.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.EndDate.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.UpdatedAt.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s SubscriptionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SubscriptionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.ServiceName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "service_name")...),
			psql.Arg(s.ServiceName),
		}})
	}

	if s.Price.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "price")...),
			psql.Arg(s.Price),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.StartDate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "start_date")...),
			psql.Arg(s.StartDate),
		}})
	}

	if s.EndDate.IsValue() || s.EndDate.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "end_date")...),
			psql.Arg(s.EndDate),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindSubscription retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSubscription(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Subscription, error) {
	if len(cols) == 0 {
		return Subscriptions.Query(
			sm.Where(Subscriptions.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Subscriptions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SubscriptionExists checks the presence of a single record by primary key
func SubscriptionExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Subscription is retrieved from the database
func (o *Subscription) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Subscriptions.AfterSelectHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Subscriptions.AfterInsertHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Subscriptions.AfterMergeHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Subscription
func (o *Subscription) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Subscription) pkEQ() dialect.Expression {
	return psql.Quote("subscriptions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Subscription
func (o *Subscription) Update(ctx context.Context, exec bob.Executor, s *SubscriptionSetter) error {
	v, err := Subscriptions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Subscription record with an executor
func (o *Subscription) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Subscriptions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Subscription using the executor
func (o *Subscription) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after SubscriptionSlice is retrieved from the database
func (o SubscriptionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Subscriptions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Subscriptions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Subscriptions.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o SubscriptionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("subscriptions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SubscriptionSlice) copyMatchingRows(from ...*Subscription) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SubscriptionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Subscriptions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Subscription:
				o.copyMatchingRows(retrieved)
			case []*Subscription:
				o.copyMatchingRows(retrieved...)
			case SubscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Subscription or a slice of Subscription
				// then run the AfterUpdateHooks on the slice
				_, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SubscriptionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Subscriptions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Subscription:
				o.copyMatchingRows(retrieved)
			case []*Subscription:
				o.copyMatchingRows(retrieved...)
			case SubscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Subscription or a slice of Subscription
				// then run the AfterDeleteHooks on the slice
				_, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o SubscriptionSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Subscriptions.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Subscription:
				o.copyMatchingRows(retrieved)
			case []*Subscription:
				o.copyMatchingRows(retrieved...)
			case SubscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Subscription or a slice of Subscription
				// then run the AfterMergeHooks on the slice
				_, err = Subscriptions.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o SubscriptionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SubscriptionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Subscriptions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SubscriptionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Subscriptions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SubscriptionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Subscriptions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type subscriptionWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	ServiceName psql.WhereMod[Q, string]
	Price       psql.WhereMod[Q, int32]
	UserID      psql.WhereMod[Q, uuid.UUID]
	StartDate   psql.WhereMod[Q, time.Time]
	EndDate     psql.WhereNullMod[Q, time.Time]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
}

func (subscriptionWhere[Q]) AliasedAs(alias string) subscriptionWhere[Q] {
	return buildSubscriptionWhere[Q](buildSubscriptionColumns(alias))
}

func buildSubscriptionWhere[Q psql.Filterable](cols subscriptionColumns) subscriptionWhere[Q] {
	return subscriptionWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](cols.ID.Expression),
		ServiceName: psql.Where[Q, string](cols.ServiceName.Expression),
		Price:       psql.Where[Q, int32](cols.Price.Expression),
		UserID:      psql.Where[Q, uuid.UUID](cols.UserID.Expression),
		StartDate:   psql.Where[Q, time.Time](cols.StartDate.Expression),
		EndDate:     psql.WhereNull[Q, time.Time](cols.EndDate.Expression),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt.Expression),
	}
}
