// Code generated by BobGen psql v0.46.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	pg_query "github.com/wasilibs/go-pgquery"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

func formatQuery(s string) (string, error) {
	aTree, err := pg_query.Parse(s)
	if err != nil {
		return "", err
	}

	return pg_query.Deparse(aTree)
}

var defaultFaker = faker.New()
