// Code generated by BobGen psql v0.46.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Subscriptions = Table[
	subscriptionColumns,
	subscriptionIndexes,
	subscriptionForeignKeys,
	subscriptionUniques,
	subscriptionChecks,
]{
	Schema: "",
	Name:   "subscriptions",
	Columns: subscriptionColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ServiceName: column{
			Name:      "service_name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Price: column{
			Name:      "price",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StartDate: column{
			Name:      "start_date",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		EndDate: column{
			Name:      "end_date",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: subscriptionIndexes{
		SubscriptionsPkey: index{
			Type: "btree",
			Name: "subscriptions_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		SubscriptionsCreatedAtIdx: index{
			Type: "btree",
			Name: "subscriptions_created_at_idx",
			Columns: []indexColumn{
				{
					Name:         "created_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		SubscriptionsServiceNameIdx: index{
			Type: "btree",
			Name: "subscriptions_service_name_idx",
			Columns: []indexColumn{
				{
					Name:         "service_name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		SubscriptionsUserIDIdx: index{
			Type: "btree",
			Name: "subscriptions_user_id_idx",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "subscriptions_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type subscriptionColumns struct {
	ID          column
	ServiceName column
	Price       column
	UserID      column
	StartDate   column
	EndDate     column
	CreatedAt   column
	UpdatedAt   column
}

func (c subscriptionColumns) AsSlice() []column {
	return []column{
		c.ID, c.ServiceName, c.Price, c.UserID, c.StartDate, c.EndDate, c.CreatedAt, c.UpdatedAt,
	}
}

type subscriptionIndexes struct {
	SubscriptionsPkey           index
	SubscriptionsCreatedAtIdx   index
	SubscriptionsServiceNameIdx index
	SubscriptionsUserIDIdx      index
}

func (i subscriptionIndexes) AsSlice() []index {
	return []index{
		i.SubscriptionsPkey, i.SubscriptionsCreatedAtIdx, i.SubscriptionsServiceNameIdx, i.SubscriptionsUserIDIdx,
	}
}

type subscriptionForeignKeys struct{}

func (f subscriptionForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type subscriptionUniques struct{}

func (u subscriptionUniques) AsSlice() []constraint {
	return []constraint{}
}

type subscriptionChecks struct{}

func (c subscriptionChecks) AsSlice() []check {
	return []check{}
}
