// Code generated by BobGen psql v0.46.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SubscriptionErrors = &subscriptionErrors{
	ErrUniqueSubscriptionsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "subscriptions",
		columns: []string{"id"},
		s:       "subscriptions_pkey",
	},
}

type subscriptionErrors struct {
	ErrUniqueSubscriptionsPkey *UniqueConstraintError
}
