// Code generated by BobGen psql v0.46.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/google/uuid"
	models "github.com/koitra/subserv/internal/dba/models"
)

type Factory struct {
	baseSubscriptionMods SubscriptionModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewSubscription(mods ...SubscriptionMod) *SubscriptionTemplate {
	return f.NewSubscriptionWithContext(context.Background(), mods...)
}

func (f *Factory) NewSubscriptionWithContext(ctx context.Context, mods ...SubscriptionMod) *SubscriptionTemplate {
	o := &SubscriptionTemplate{f: f}

	if f != nil {
		f.baseSubscriptionMods.Apply(ctx, o)
	}

	SubscriptionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSubscription(ctx context.Context, m *models.Subscription) *SubscriptionTemplate {
	return f.fromExistingSubscription(ctx, m)
}

func (f *Factory) fromExistingSubscription(ctx context.Context, m *models.Subscription) *SubscriptionTemplate {
	o := &SubscriptionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() uuid.UUID { return m.ID }
	o.ServiceName = func() string { return m.ServiceName }
	o.Price = func() int32 { return m.Price }
	o.UserID = func() uuid.UUID { return m.UserID }
	o.StartDate = func() time.Time { return m.StartDate }
	o.EndDate = func() null.Val[time.Time] { return m.EndDate }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) ClearBaseSubscriptionMods() {
	f.baseSubscriptionMods = nil
}

func (f *Factory) AddBaseSubscriptionMod(mods ...SubscriptionMod) {
	f.baseSubscriptionMods = append(f.baseSubscriptionMods, mods...)
}
