// Code generated by BobGen psql v0.46.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/jaswdr/faker/v2"
	models "github.com/koitra/subserv/internal/dba/models"
	"github.com/stephenafamo/bob"
)

type SubscriptionMod interface {
	Apply(context.Context, *SubscriptionTemplate)
}

type SubscriptionModFunc func(context.Context, *SubscriptionTemplate)

func (f SubscriptionModFunc) Apply(ctx context.Context, n *SubscriptionTemplate) {
	f(ctx, n)
}

type SubscriptionModSlice []SubscriptionMod

func (mods SubscriptionModSlice) Apply(ctx context.Context, n *SubscriptionTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// SubscriptionTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type SubscriptionTemplate struct {
	ID          func() uuid.UUID
	ServiceName func() string
	Price       func() int32
	UserID      func() uuid.UUID
	StartDate   func() time.Time
	EndDate     func() null.Val[time.Time]
	CreatedAt   func() time.Time
	UpdatedAt   func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the SubscriptionTemplate
func (o *SubscriptionTemplate) Apply(ctx context.Context, mods ...SubscriptionMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Subscription
// according to the relationships in the template. Nothing is inserted into the db
func (t SubscriptionTemplate) setModelRels(o *models.Subscription) {}

// BuildSetter returns an *models.SubscriptionSetter
// this does nothing with the relationship templates
func (o SubscriptionTemplate) BuildSetter() *models.SubscriptionSetter {
	m := &models.SubscriptionSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.ServiceName != nil {
		val := o.ServiceName()
		m.ServiceName = omit.From(val)
	}
	if o.Price != nil {
		val := o.Price()
		m.Price = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.StartDate != nil {
		val := o.StartDate()
		m.StartDate = omit.From(val)
	}
	if o.EndDate != nil {
		val := o.EndDate()
		m.EndDate = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.SubscriptionSetter
// this does nothing with the relationship templates
func (o SubscriptionTemplate) BuildManySetter(number int) []*models.SubscriptionSetter {
	m := make([]*models.SubscriptionSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Subscription
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SubscriptionTemplate.Create
func (o SubscriptionTemplate) Build() *models.Subscription {
	m := &models.Subscription{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.ServiceName != nil {
		m.ServiceName = o.ServiceName()
	}
	if o.Price != nil {
		m.Price = o.Price()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.StartDate != nil {
		m.StartDate = o.StartDate()
	}
	if o.EndDate != nil {
		m.EndDate = o.EndDate()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.SubscriptionSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SubscriptionTemplate.CreateMany
func (o SubscriptionTemplate) BuildMany(number int) models.SubscriptionSlice {
	m := make(models.SubscriptionSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableSubscription(m *models.SubscriptionSetter) {
	if m.ID.IsUnset() {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if m.ServiceName.IsUnset() {
		val := random_string(nil)
		m.ServiceName = omit.From(val)
	}
	if m.Price.IsUnset() {
		val := random_int32(nil)
		m.Price = omit.From(val)
	}
	if m.UserID.IsUnset() {
		val := random_uuid_UUID(nil)
		m.UserID = omit.From(val)
	}
	if m.StartDate.IsUnset() {
		val := random_time_Time(nil)
		m.StartDate = omit.From(val)
	}
	if m.CreatedAt.IsUnset() {
		val := random_time_Time(nil)
		m.CreatedAt = omit.From(val)
	}
	if m.UpdatedAt.IsUnset() {
		val := random_time_Time(nil)
		m.UpdatedAt = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Subscription
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *SubscriptionTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Subscription) error {
	var err error

	return err
}

// Create builds a subscription and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *SubscriptionTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Subscription, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableSubscription(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.Subscriptions.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a subscription and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *SubscriptionTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Subscription {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a subscription and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *SubscriptionTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Subscription {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple subscriptions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o SubscriptionTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.SubscriptionSlice, error) {
	var err error
	m := make(models.SubscriptionSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple subscriptions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o SubscriptionTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.SubscriptionSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple subscriptions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o SubscriptionTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.SubscriptionSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Subscription has methods that act as mods for the SubscriptionTemplate
var SubscriptionMods subscriptionMods

type subscriptionMods struct{}

func (m subscriptionMods) RandomizeAllColumns(f *faker.Faker) SubscriptionMod {
	return SubscriptionModSlice{
		SubscriptionMods.RandomID(f),
		SubscriptionMods.RandomServiceName(f),
		SubscriptionMods.RandomPrice(f),
		SubscriptionMods.RandomUserID(f),
		SubscriptionMods.RandomStartDate(f),
		SubscriptionMods.RandomEndDate(f),
		SubscriptionMods.RandomCreatedAt(f),
		SubscriptionMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m subscriptionMods) ID(val uuid.UUID) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) IDFunc(f func() uuid.UUID) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetID() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomID(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) ServiceName(val string) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ServiceName = func() string { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) ServiceNameFunc(f func() string) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ServiceName = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetServiceName() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ServiceName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomServiceName(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ServiceName = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) Price(val int32) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.Price = func() int32 { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) PriceFunc(f func() int32) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.Price = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetPrice() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.Price = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomPrice(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.Price = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) UserID(val uuid.UUID) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UserID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) UserIDFunc(f func() uuid.UUID) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetUserID() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomUserID(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UserID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) StartDate(val time.Time) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.StartDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) StartDateFunc(f func() time.Time) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.StartDate = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetStartDate() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.StartDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomStartDate(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.StartDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) EndDate(val null.Val[time.Time]) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.EndDate = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) EndDateFunc(f func() null.Val[time.Time]) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.EndDate = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetEndDate() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.EndDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m subscriptionMods) RandomEndDate(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.EndDate = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m subscriptionMods) RandomEndDateNotNull(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.EndDate = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) CreatedAt(val time.Time) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) CreatedAtFunc(f func() time.Time) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetCreatedAt() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomCreatedAt(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) UpdatedAt(val time.Time) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) UpdatedAtFunc(f func() time.Time) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetUpdatedAt() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomUpdatedAt(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m subscriptionMods) WithParentsCascading() SubscriptionMod {
	return SubscriptionModFunc(func(ctx context.Context, o *SubscriptionTemplate) {
		if isDone, _ := subscriptionWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = subscriptionWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
